'use client';
import { FormEvent, useEffect, useMemo, useState } from 'react';

const materials = {
  profile_one: { label: 'Профлист односторонний', prices: { '1.8': 1900, '2': 2100 } }, profile_two: { label: 'Профлист двусторонний', prices: { '1.8': 2200, '2': 2400 } }, picket_single: { label: 'Евроштакетник, один ряд', prices: { '1.8': 2150, '2': 2300 } }, picket_chess: { label: 'Евроштакетник, шахматка', prices: { '1.8': 3650, '2': 3900 } }, mesh3d: { label: '3D-сетка', prices: { '1.7': 1900, '2': 2000 } }, chainlink: { label: 'Сетка-рабица', prices: { '1.8': 900, '2': 1000 } }, frame: { label: 'Каркас забора', prices: { '1.8': 1250, '2': 1400 } },
} as const;
type Material = keyof typeof materials; type State = { material: Material; height: string; length: number; gate: 'swing'|'sliding'; width: string; wicket: 'adjacent'|'separate'; extension: number; paint: number };
const initial: State = { material: 'profile_one', height: '2', length: 70, gate: 'swing', width: '4', wicket: 'adjacent', extension: 0, paint: 0 };
const money = (n:number) => new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(n);

export default function Home() {
  const [s,setS]=useState<State>(initial), [result,setResult]=useState(false), [error,setError]=useState('');
  useEffect(()=>{const stored=localStorage.getItem('fence-estimate');if(stored)setS(JSON.parse(stored));navigator.serviceWorker?.register('/sw.js')},[]);
  useEffect(()=>localStorage.setItem('fence-estimate',JSON.stringify(s)),[s]);
  const q=useMemo(()=>{const rate=materials[s.material].prices[s.height as keyof typeof materials[typeof s.material]['prices']] as number;const gate=s.gate==='sliding'?(s.width==='5'?75000:69000):(s.width==='5'?23000:17000);const wicket=s.wicket==='separate'?15000:13000;const delivery=s.length<=60?6000:s.length<=120?8000:12000;const rows=[{label:`${materials[s.material].label}, ${s.height.replace('.',',')} м`,amount:s.length*rate},{label:`${s.gate==='sliding'?'Откатные':'Распашные'} ворота ${s.width} м`,amount:gate},{label:s.wicket==='separate'?'Калитка отдельно стоящая':'Калитка рядом с воротами',amount:wicket},{label:'Доставка',amount:delivery},...(s.extension?[{label:'Удлинение столбов',amount:s.extension*300}]:[]),...(s.paint?[{label:'Покраска каркаса',amount:s.paint*250}]:[])];return{rows,total:rows.reduce((a,b)=>a+b.amount,0)}},[s]);
  const change=<K extends keyof State>(key:K,value:State[K])=>setS(prev=>({...prev,[key]:value}));
  const submit=(e:FormEvent)=>{e.preventDefault();if(s.length<30){setError('Авторасчёт доступен от 30 м. Для меньшей длины нужна ручная смета.');return}setError('');setResult(true)};
  if(result)return <main className="result"><button className="back" onClick={()=>setResult(false)}>‹ Изменить расчёт</button><article className="quote"><header><span className="mark">⌁</span><div><small>Предварительный расчёт</small><strong>Смета забора</strong></div><time>{new Date().toLocaleDateString('ru-RU')}</time></header><section className="total"><small>Итого</small><b>{money(q.total)}</b><span>Общая длина — {s.length} м</span></section><div className="rows">{q.rows.map(r=><div key={r.label}><span>{r.label}</span><b>{money(r.amount)}</b></div>)}</div><footer><b>Предварительная стоимость</b><p>Точную стоимость и состав работ подтвердим после выездного замера.</p></footer></article><button className="primary" onClick={()=>navigator.share?.({title:'Смета забора',text:`Предварительная смета: ${money(q.total)}`})}>Поделиться</button><p>Сделайте скриншот карточки или отправьте результат через «Поделиться».</p></main>;
  return <main className="app"><header className="head"><span className="mark">⌁</span><div><small>Локальный расчёт</small><h1>Смета забора</h1></div></header><section className="hero"><span>Предварительная смета</span><b>{money(q.total)}</b></section><form onSubmit={submit}><section className="card"><small>01 · Участок забора</small><label>Материал<select value={s.material} onChange={e=>{const material=e.target.value as Material;change('material',material);change('height',Object.keys(materials[material].prices)[0])}}>{Object.entries(materials).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label><div className="grid"><label>Высота, м<select value={s.height} onChange={e=>change('height',e.target.value)}>{Object.keys(materials[s.material].prices).map(h=><option key={h} value={h}>{h.replace('.',',')}</option>)}</select></label><label>Длина, м<input type="number" min="1" value={s.length} onChange={e=>change('length',Number(e.target.value))}/></label></div></section><section className="card"><small>02 · Ворота и калитка</small><div className="grid"><label>Тип ворот<select value={s.gate} onChange={e=>change('gate',e.target.value as State['gate'])}><option value="swing">Распашные</option><option value="sliding">Откатные</option></select></label><label>Ширина, м<select value={s.width} onChange={e=>change('width',e.target.value)}>{['3','3.5','4','5'].map(v=><option key={v} value={v}>{v.replace('.',',')}</option>)}</select></label></div><label>Калитка<select value={s.wicket} onChange={e=>change('wicket',e.target.value as State['wicket'])}><option value="adjacent">Рядом с воротами</option><option value="separate">Отдельно стоящая</option></select></label></section><section className="card"><small>03 · Дополнительно</small><div className="grid"><label>Удлинение столбов, м<input type="number" min="0" value={s.extension} onChange={e=>change('extension',Number(e.target.value))}/></label><label>Покраска каркаса, м<input type="number" min="0" value={s.paint} onChange={e=>change('paint',Number(e.target.value))}/></label></div></section>{error&&<p className="error">{error}</p>}<button className="primary">Показать результат →</button><button type="button" className="reset" onClick={()=>setS(initial)}>Сбросить</button></form><p className="note">Без CRM и n8n · данные остаются на устройстве</p><details><summary>Как установить на iPhone</summary><p>Откройте сайт в Safari → «Поделиться» → «На экран Домой». После первого открытия расчёт работает офлайн.</p></details></main>;
}
